#!/usr/bin/env bash
# hedge serving benchmark
#
# provisions everything the matrix needs and then hands off to bench.py, which
# owns the measurement. nothing here is measured: tool downloads, certificate
# generation and content generation all happen before the first server starts.
#
#   ./doc/bench/run.sh              run the full matrix and write a results file
#   ./doc/bench/run.sh --smoke      one short cell per protocol, no results file
#
# HEDGE_BINARY overrides the server under test. Anything else is provisioned
# here at a pinned version, so two runs on the same machine compare.

set -eu

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
bench="$root/doc/bench"
tool="$bench/.tool"
work="$bench/.work"

OHA_VERSION="1.16.0"
CADDY_VERSION="2.11.4"

hedge_binary="${HEDGE_BINARY:-$root/out/linux-x86_64/release/bin/hedge}"

say() { printf '%s\n' "$*" >&2; }

# --- the server under test ---------------------------------------------------

if [ ! -x "$hedge_binary" ]; then
    say "building hedge (release)"
    mach build "$root" --profile release
fi
if [ ! -x "$hedge_binary" ]; then
    say "no hedge binary at $hedge_binary"
    exit 1
fi

# --- pinned comparison tools -------------------------------------------------

mkdir -p "$tool"

if [ ! -x "$tool/oha" ]; then
    say "downloading oha v$OHA_VERSION"
    gh release download "v$OHA_VERSION" --repo hatoo/oha \
        --pattern 'oha-linux-amd64' --dir "$tool" --clobber
    mv "$tool/oha-linux-amd64" "$tool/oha"
    chmod +x "$tool/oha"
fi

if [ ! -x "$tool/caddy" ]; then
    say "downloading caddy v$CADDY_VERSION"
    gh release download "v$CADDY_VERSION" --repo caddyserver/caddy \
        --pattern "caddy_${CADDY_VERSION}_linux_amd64.tar.gz" --dir "$tool" --clobber
    tar xzf "$tool/caddy_${CADDY_VERSION}_linux_amd64.tar.gz" -C "$tool" caddy
    rm -f "$tool/caddy_${CADDY_VERSION}_linux_amd64.tar.gz"
    chmod +x "$tool/caddy"
fi

# --- content -----------------------------------------------------------------
#
# one directory, served by both servers. the bodies are incompressible random
# bytes so that a server which negotiated compression could not win the transfer
# columns by sending less; the load generator also asks for no compression.

content="$work/content"
mkdir -p "$content"
for spec in 1k:1024 64k:65536 1m:1048576; do
    name="${spec%%:*}"
    size="${spec##*:}"
    if [ ! -f "$content/$name" ] || \
       [ "$(stat -c %s "$content/$name")" != "$size" ]; then
        head -c "$size" /dev/urandom > "$content/$name"
    fi
done

# --- credentials -------------------------------------------------------------
#
# one self-signed P-256 leaf for localhost, presented by both servers, so the
# TLS columns differ by implementation and not by key type or chain length.
# P-256 because it is what a real deployment is most likely to hold; hedge also
# accepts Ed25519 and RSA leaves.

certs="$work/certs"
mkdir -p "$certs"
if [ ! -f "$certs/bench.pem" ] || [ ! -f "$certs/bench.key" ]; then
    say "generating a self-signed P-256 certificate for localhost"
    openssl req -x509 -newkey ec -pkeyopt ec_paramgen_curve:prime256v1 \
        -sha256 -days 365 -nodes \
        -keyout "$certs/bench.key" -out "$certs/bench.pem" \
        -subj "/CN=localhost" \
        -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" \
        -addext "keyUsage=digitalSignature" \
        -addext "extendedKeyUsage=serverAuth" >/dev/null 2>&1
    openssl pkcs8 -topk8 -nocrypt -in "$certs/bench.key" \
        -out "$certs/bench.pk8.key" >/dev/null 2>&1
    mv "$certs/bench.pk8.key" "$certs/bench.key"
    chmod 600 "$certs/bench.key"
fi

# --- server configurations ---------------------------------------------------
#
# written here rather than checked in, because both carry absolute paths to the
# generated content and credentials. the ports are the contract between these
# two files and bench.py.

cat > "$work/hedge.toml" <<EOF
# generated by doc/bench/run.sh

[server]
name = "bench"

# every connection in this benchmark comes from 127.0.0.1, so the whole load is
# one peer. hedge defaults to 100 connections per peer, which is an anti-abuse
# bound and the right default for a public listener; left alone it would refuse
# the 256-connection column outright and the number would describe the bound
# rather than the server. Caddy applies no equivalent default, so raising it is
# what makes the two comparable.
[server.limits]
max_connections = 10000
max_connections_per_peer = 1024

[[listener]]
name = "cleartext"
address = "127.0.0.1:18080"
protocols = ["http/1.1", "h2"]

[[listener]]
name = "secure"
address = "127.0.0.1:18443"
protocols = ["http/1.1", "h2"]
tls = "bench"

[[listener]]
name = "quic"
address = "127.0.0.1:18443"
transport = "quic"
protocols = ["h3"]
tls = "bench"

[tls.bench]
identity = [
  { server_name = "localhost", certificate = "$certs/bench.pem", key = "$certs/bench.key" },
]
default = "localhost"

# one host owns the routes. the other two attach the same name to the other
# listeners so each has a TLS policy and a name to check; routing itself carries
# no listener dimension, so the routes below serve every listener.
[host.site]
listener = "secure"
server_name = "localhost"

[host.plain]
listener = "cleartext"
server_name = "localhost"

[host.h3]
listener = "quic"
server_name = "localhost"

[service.files]
kind = "static"
root = "$content"

[[route]]
name = "files"
host = "site"
path = "/**"
service = "files"
EOF

cat > "$work/Caddyfile" <<EOF
# generated by doc/bench/run.sh

{
	auto_https off
	admin off
	persist_config off
	log {
		output discard
	}
	servers {
		protocols h1 h2 h3
	}
}

http://localhost:18081 {
	root * $content
	file_server
}

https://localhost:18444 {
	tls $certs/bench.pem $certs/bench.key
	root * $content
	file_server
}
EOF

# caddy keeps state under these regardless of admin/persist settings; keeping
# them inside .work stops a benchmark run writing into the operator's home.
export XDG_CONFIG_HOME="$work/caddy-config"
export XDG_DATA_HOME="$work/caddy-data"
mkdir -p "$XDG_CONFIG_HOME" "$XDG_DATA_HOME"

# --- the matrix --------------------------------------------------------------

exec python3 "$bench/bench.py" \
    --root "$root" \
    --hedge-binary "$hedge_binary" \
    --oha "$tool/oha" \
    --caddy "$tool/caddy" \
    --hedge-config "$work/hedge.toml" \
    --caddyfile "$work/Caddyfile" \
    --content "$content" \
    --work "$work" \
    "$@"
